name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libyaml-dev libjansson-dev

      - name: Build
        run: make

      - name: Create tarball
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          DIST="udp-server-${VERSION}"
          mkdir -p ${DIST}
          cp udp_server udp_client config.yaml README.md LICENSE ${DIST}/
          tar czf "${DIST}.tar.gz" ${DIST}
          echo "::set-output name=tarball::${DIST}.tar.gz"
          echo "::set-output name=version::${VERSION}"
        id: tarball

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tarball.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.tarball.outputs.tarball }}
          asset_name: ${{ steps.tarball.outputs.tarball }}
          asset_content_type: application/gzip
